name: {{ cookiecutter.repo_name }}

channels:
  - r
  - conda-forge

dependencies:
  - python=3.7
  - numba
  - pandas
  - numpy
  - matplotlib
  - scipy
  - notebook
  - rpy2
  - cookiecutter
  - sphinx
  - sphinx_rtd_theme
  - recommonmark
  -
